### ISSUE TITLE
How to Generate Graph From More Than One saFile

### ISSUE THREAD

**Issue by ajihandoko** [juliojsb/sarviewer#7]
Hai julio, It's so interested project from your repository.  
In my case I have to generate graphics for a month. So that more than one sa file generated in its graphic. what command should I run to generate more than one sa file? 

In existing environment, I convert sa file to sar file, then i merge sar file into one file example sarMerge.txt. And then generate graphic from sarMerge.txt using kSar-2.0. 

Big thanks for your help.

**Comment by juliojsb** [comment]
Hi,

In /etc/sysstat/sysstat you can specify HISTORY for the retention of log files:

```
# sysstat configuration file. See sysstat(5) manual page.                                                                                                                                                          

# How long to keep log files (in days).
# Used by sa2(8) script
# If value is greater than 28, then log files are kept in
# multiple directories, one for each month.
HISTORY=31
```
That would generate one log file per day:

```
[root@jota-pc sysstat]# ls -lrht /var/log/sysstat/
-rw-r--r-- 1 root root 537K Apr 20 00:00 sa20180419
-rw-r--r-- 1 root root 678K Apr 20 00:10 sar20180419
-rw-r--r-- 1 root root 815K Apr 21 00:00 sa20180420
-rw-r--r-- 1 root root 1.1M Apr 21 00:08 sar20180420
-rw-r--r-- 1 root root 2.0M Apr 22 00:00 sa20180421
-rw-r--r-- 1 root root 2.5M Apr 22 00:08 sar20180421
-rw-r--r-- 1 root root 1.9M Apr 23 00:00 sa20180422
-rw-r--r-- 1 root root 2.2M Apr 23 00:09 sar20180422
-rw-r--r-- 1 root root 425K Apr 23 18:45 sa20180423
```
Each file should be parsed individually. I know no other way.

This repository is intended for daily stats. Since month stats would change the way of parsing dates (we would need to consider day of the stats and not only Hour:Minute:Seconds) a major rework of scripts and plotters would be needed.

Regards,
